// my-nuxt-app/src/pages/lgn/lgn01001s01.vue
<template>
  <div class="container input-form">
    <Form ref="form">
      <div class="row">
        <div class="col-2 head">
          아이디
        </div>
        <div class="col">
          <Input
            type="text"
            label="아이디"
            name="userId"
            maxlength="32"
            v-model="userInfo.userId"
            validrules="required|len:4,32"
            />
        </div>
      </div>
      <div class="row">
        <div class="col-2 head">
          비밀번호
        </div>
        <div class="col">
          <Input
            type="password"
            label="비밀번호"
            name="passwd"
            maxlength="32"
            v-model="userInfo.passwd"
            validrules="required|len:4,32"
            />
        </div>
      </div>
      <div class="row">
        <div class="col-2 head">
          로그인
        </div>
        <div class="col">
          <Button
            class="btn-primary mx-1"
            @click="login()"
            >
            로그인
          </Button>
        </div>
      </div>
    </Form>
  </div>
</template>
<script setup lang="ts">
import * as C from '@/libs/constants'
import { inst } from '@/store/commons/basesystem'
import log from '@/libs/log'
import values from '@/libs/values'
import api from '@/libs/api'

import Button from '@/components/button.vue'
import Input from '@/components/input.vue'
import Form from '@/components/form.vue'

import { useUserInfo } from '@/store/commons/userinfo'
import dialog from '@/libs/dialog-context'

const self = inst(getCurrentInstance())
const pageTitle = '로그인'

const form = ref()

const userInfo = ref({
  userId: '',
  userNm: '',
  passwd: ''
})

const ustore = useUserInfo()

const login = async () => {
  if (await form.value.validate()) {
    const data = values.clone(userInfo.value)
    // data.passwd = values.enc(data.passwd)
    data.passwd = ''

    const res = await api.post('lgn01001', data, { noerr: true })
    ustore.userId = userInfo.value.userId
    ustore.userNm = res.userNm
    ustore.expireTime = new Date().getTime() + C.SESSION_TIMEOUT
    await dialog.alert('로그인 되었습니다')
    await self.removeHist()
    // await dialog.alert('로그인에 실패하였습니다')
  }
}

defineExpose({ pageTitle })
</script>

// src/pages/lgn/lgn01001s01.jsx
import app from '@/libs/app-context'
import api from '@/libs/api'
import crypto from '@/libs/crypto'
import * as C from '@/libs/constants'
import { Form, Block, Button, Container, Input } from '@/components'

const { definePage, useSetup, clone, log, getConfig, goPage } = app

export default definePage(() => {

  const self = useSetup({
    vars: {
      formdata: {
        userId: '',
        passwd: '',
      },
      aeskey: '',
    }
  })

  const { vars } = self()

  const submit = async () => {
    const formdata = clone (vars.formdata)
    formdata.passwd = crypto.aes.encrypt(formdata.passwd)
    try {
      const res = await api.post(`lgn01001`, formdata)
      log.debug('RES:', res)
      if (res.rescd === '0000') {
        goPage(-1)
      } else {
        alert('로그인이 실패했습니다')
      }
    } catch (e) { log.debug('E:', e) }
  }

  return (
  <Container id='usr01001s01'>
    <section className='title'>
      <h2>로그인</h2>
    </section>
    <hr/>
    <section className='flex-form'>
      <Form>
        <article className='text-center'>
          <Block>
            <p>
            </p>
          </Block>
          <Block className='form-block'>
            <label htmlFor='frm-user-id'> 아이디 </label>
            <Block className='form-element'>
            <Input
              id='frm-user-id'
              model={ vars.formdata }
              name='userId'
              placeholder='로그인 아이디'
              maxLength={ 20 }
              className='w-full'
              size='small'
              onEnter={ submit }
              />
            </Block>
          </Block>
          <Block className='form-block'>
            <label htmlFor='frm-passwd'> 비밀번호 </label>
            <Block className='form-element'>
            <Input
              id='frm-passwd'
              type='password'
              model={ vars.formdata }
              name='passwd'
              placeholder='비밀번호'
              maxLength={ 20 }
              className='w-full'
              size='small'
              onEnter={ submit }
              />
            </Block>
          </Block>
          <hr/>
          <Block className='buttons'>
            <Button
              className='mx-1'
              variant='contained'
              size='large'
              onClick={ submit }
              >
              로그인
            </Button>
            <Button
              className='mx-1'
              variant='outlined'
              size='large'
              >
              취소
            </Button>
          </Block>
        </article>
      </Form>
    </section>
  </Container>
  )
})
