// my-nuxt-app/src/pages/atc/atc01001s04/[pagenum].vue
<template>
  <div class="container board-list">
    <div class="row head">
        <div class="col-1">
          번호
        </div>
        <div class="col">
          제목
        </div>
        <div class="col-2">
          작성자
        </div>
        <div class="col-2">
          작성일자
        </div>
    </div>
    <template v-if="!(boardData?.list?.length)">
      <div class="row">
        <div class="col text-center">
          게시물이 없습니다.
        </div>
      </div>
    </template>
    <template v-for="(itm, inx) in boardData.list" key="inx">
      <div class="row">
        <div class="col-1">
          {{ paging.rnums(boardData.page)[0] + inx }}
        </div>
        <div class="col cursor-pointer"
          @click="viewArticle(itm)"
          >
          {{ itm.title }}
        </div>
        <div class="col-2">
          {{ itm.userNm }}
          <template v-if="itm.userId">
            ({{ itm.userId }})
          </template>
        </div>
        <div class="col-2">
          {{ $f('dt', itm.ctime) }}
        </div>
      </div>
    </template>
    <div class="mt-2">
      <Button
        class="btn-primary"
        @click="newArticle()"
        >
        새글작성
      </Button>
    </div>
  </div>
  <div class="mt-3 text-center pagination">
    <nav>
      <ul class="pagination">
        <li class="page-item">
          <Button flat
            class="page-link"
            :disabled="Number(boardData.page) < 5"
            @click="search({ page: Number(boardData.page) - Number(boardData.pages) }, true)"
            >
            &lt;&lt;
          </Button>
        </li>
        <li class="page-item">
          <Button flat
            class="page-link"
            :disabled="Number(boardData.page) <= 1"
            @click="search({ page: Number(boardData.page) - 1 }, true)"
            >
            &lt;
          </Button>
        </li>
        <template v-for="inx in range(paging.pnums(boardData.page))">
          <li :class="{ 'page-item': true, active: boardData.page == String(inx) }">
            <Button flat
              @click="search({ page: inx }, true)"
              class="page-link"
              >
              {{ inx }}
            </Button>
          </li>
        </template>
        <li class="page-item">
          <Button flat
            class="page-link"
            :disabled="Number(boardData.page) >= Number(boardData.totp)"
            @click="search({ page: Number(boardData.page) + 1 }, true)"
            >
            &gt;
          </Button>
        </li>
        <li class="page-item">
          <Button flat
            class="page-link"
            :disabled="Number(boardData.page) >= (Number(boardData.totp) - Number(boardData.pages) + 1)"
            @click="search({ page: Number(boardData.page) + Number(boardData.pages) }, true)"
            >
            &gt;&gt;
          </Button>
        </li>
      </ul>
    </nav>
  </div>
</template>
<script setup lang="ts">

import * as C from '@/libs/constants'
import log from '@/libs/log'
import { useBaseSystem, inst } from '@/store/commons/basesystem'
import api from '@/libs/api'
import { $f } from '@/libs/format'
import values from '@/libs/values'
import { Paging } from '@/libs/paging'

import Button from '@/components/button.vue'
import dialog from '@/libs/dialog-context'

const self = inst(getCurrentInstance())
const pageTitle = '게시판'
const boardData = ref({ list: [] as any[] } as any)
const { range } = values
const paging = ref(new Paging())
const sys = useBaseSystem()

watch(() => sys.$state?.popstate, (e: any) => {
  let data = {
    currentPage: 1,
    rowCount: 10,
    rowStart: 0,
    rowTotal: 0,
    keyword: '',
    searchType: '',
    orderType: ''
  }
  if (e?.state?.histdata) { data = JSON.parse(e.state.histdata) }
  search(data)
}, { deep: true })

onMounted(async () => {
  const pagenum = self.getParameter('pagenum')
  let data = {
    currentPage: 1,
    rowCount: 10,
    rowStart: 0,
    rowTotal: 0,
    keyword: '',
    searchType: '',
    orderType: ''
  }
  if (history?.state?.histdata) { data = JSON.parse(history.state.histdata) }
  search(data)
})

const search = async (req: any, save?: boolean) => {
  const data = await api.post('atc01001', req)
  if (save) { self.saveHist(req) }
  paging.value = new Paging(data.rows, data.pages, data.cnt)
  data.totp = Math.ceil(Number(data.cnt) / Number(data.rows))
  boardData.value = data
}

const viewArticle = async (item: any) => {
  self.goPage(`/atc/atc01001s02/${item?.id}`)
}

const newArticle = async () => {
  self.goPage(`/atc/atc01001s03/_`)
}

defineExpose({ pageTitle })
</script>

// src/pages/atc/atc01001s04/[pagenum].jsx
import app from '@/libs/app-context'
import api from '@/libs/api'
import * as C from '@/libs/constants'
import { Container, Block, Button, Pagination, Link } from '@/components'
import moment from 'moment'

const { definePage, useSetup, log, clone, getParameter, goPage } = app


export default definePage(() => {
  const self = useSetup({
    vars: {
      data: {
        list: [],
      },
      pdata: {
        currentPage: 1,
        rowCount: 10,
        rowStart: 0,
        rowTotal: 0,
        keyword: '',
        searchType: '',
        orderType: ''
      },
      state: 0,
    },
    async mounted() {
      loadData(getParameter('pagenum') || 1)
    },
  })

  const { vars, update } = self()

  const print = {
    num: (inx) => (vars.pdata?.rowTotal || 0) - (vars.pdata?.rowStart || 0) - inx,
    cdate: (date) => date && moment(date).format('YYYY-MM-DD'),
    state(state) {
      switch (state) {
      case 0: return '잠시만 기다려 주세요.'
      case 2: return '검색된 게시물이 없습니다.'
      default: return state
      }
    }
  }

  const loadData = async (pagenum = C.UNDEFINED) => {
    vars.state = 0
    update(C.UPDATE_FULL)
    try {
      if (pagenum !== C.UNDEFINED) {
        vars.pdata.rowStart = ((pagenum - 1) || 0) * vars.pdata.rowCount
      }
      const pdata = clone(vars.pdata)
      const res = await api.post(`atc01001`, pdata)
      log.debug('RES:', res)
      vars.data = res
      if (vars.data.list.length != 0) {
        vars.state = 1
        vars.pdata.currentPage = pagenum
      } else {
        vars.state = 2
      }
      for (const k in vars.pdata) { Object.hasOwn(res, k) && (vars.pdata[k] = res[k]) }
    } catch (e) {
      vars.data.list = []
      vars.state = e?.message || '오류가 발생했습니다.'
      log.debug('E:', e)
    }
    update(C.UPDATE_FULL)
  }

  const pageChanged = async () => {
    goPage(`/atc/atc01001s04/${vars.pdata.currentPage}`)
  }
  return (
  <Container>
    <section className='title'>
      <h2>게시물 목록</h2>
      <Button
        variant='contained'
        href='/atc/atc01001s01'
        >
        새글작성
      </Button>
    </section>
    <hr/>
    <section>
      <article>
        <Block>
          <table className='w-full articles'>
            <colgroup>
              <col width={'10%'} />
              <col width={'50%'} />
              <col width={'20%'} />
              <col width={'20%'} />
            </colgroup>
            <thead>
              <tr>
                <th> 순번 </th>
                <th> 제목 </th>
                <th> 작성자 </th>
                <th> 작성일 </th>
              </tr>
            </thead>
            <tbody>
            <tr><td colSpan={4} className='nopad'><hr/></td></tr>
            { (vars.data?.list?.length || 0) === 0 && (
              <tr><td colSpan={4} className='text-center'>{
                print.state(vars.state)
              }</td></tr>
            ) }
            { vars.data?.list?.map((itm, inx) => (
              <tr key={ inx }>
                <td className='text-right'> { print.num(inx) } </td>
                <td>
                  <Link
                    href={ `/atc/atc01001s03/${itm.id}` }
                    >
                    { itm?.title }
                  </Link>
                </td>
                <td> { itm?.userNm } </td>
                <td> { print.cdate(itm?.ctime) } </td>
              </tr>
            )) }
            </tbody>
          </table>
        </Block>
        <Block className='flex justify-center'>
          <Pagination
            model={ vars.pdata }
            onChange={ pageChanged }
            />
        </Block>
      </article>
    </section>
  </Container>
  )
})
