// my-nuxt-app/pages/atc/atc01001s02/[articleId].vue
<template>
  <div class="container board-article">
    <div class="row">
      <div class="col-2 head">
        제목
      </div>
      <div class="col">
        {{ data.title }}
      </div>
    </div>
    <div class="row content">
      <div class="col-2 head">
        내용
      </div>
      <div class="col" v-html="data.contents"></div>
    </div>
    <template v-if="data.userNm">
    <div class="row">
      <div class="col-2 head">
        작성자
      </div>
      <div class="col">
        {{ data.userNm }} 
        <template v-if="data.userId">
        ({{ data.userId }})
        </template>
      </div>
    </div>
    </template>
    <div class="row">
      <div class="col-2 head">
        작성일자 / 수정일자
      </div>
      <div class="col">
        {{ $f('dt', data.ctime) }} /
        {{ $f('dt', data.utime) }}
      </div>
    </div>
    <div class="row">
      <div class="col-2 head">
        수정
      </div>
      <div class="col">
        <Button
          class="btn-primary mx-1"
          @click="editArticle(data.id)"
          >
          수정
        </Button>
        <Button
          class="btn-danger mx-1"
          @click="deleteArticle(data.id)"
          >
          삭제
        </Button>
        <Button
          class="btn-secondary mx-1"
          @click="self.goPage('/atc/atc01001s04/1')"
          >
          목록보기
        </Button>
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import * as C from '@/libs/constants'
import { inst } from '@/store/commons/basesystem'
import log from '@/libs/log'
import api from '@/libs/api'
import proc from '@/libs/proc'
import { $f } from '@/libs/format'

import Button from '@/components/button.vue'
import dialog from '@/libs/dialog'

const self = inst(getCurrentInstance())

const pageTitle = ref('상세보기')

const data = ref({} as any)

onMounted(async() => {
  await getArticle()
})

const getArticle = async () => {
  log.debug('GET-ARTICLE...')
  const id = self.getParameter('articleId')
  data.value = await api.get(`atc01001/${id}`, {})
}

const editArticle = async (id: string) => {
  self.goPage(`/atc/atc01001s03/${id}`)
}

const deleteArticle = async (id: string) => {
  if (await dialog.confirm(`"${data.value.title || ''}" 게시글을 삭제하시겠습니까?`)) {
    await api.delete(`atc01001/${id}`, {})
    await dialog.alert('삭제가 완료되었습니다')
    await self.removeHist()
  }
}

defineExpose({ pageTitle })
</script>

// src/pages/atc/atc01001s03/[articleid].jsx
import app from '@/libs/app-context'
import api from '@/libs/api'
import * as C from '@/libs/constants'
import userContext from '@/libs/user-context'
import { Container, Block, Button, Link, Content } from '@/components'
import moment from 'moment'

const { definePage, useSetup, log, putAll, clone, getParameter, goPage } = app

export default definePage(() => {
  const self = useSetup({
    vars: {
      data: {
        id: '',
        title: '',
        contents: '',
        userId: '',
        userNm: '',
        ctime: ''
      },
    },
    async mounted() {
      loadData(getParameter('articleid'))
    }
  })
  const userInfo = userContext.getUserInfo()
  const { vars, update, ready } = self()

  const loadData = async (articleId) => {
    const res = await api.get(`atc01001/${articleId}`)
    vars.data = clone(res)
    log.debug('RES:', res)
    update(C.UPDATE_FULL)
  }

  const print = {
    cdate: (date) => date && moment(date).format('YYYY-MM-DD'),
  }
  return (
  <Container>
    <section className='title'>
      <h2>{ vars.data?.title || '게시물 조회' }</h2>
      { ready() && (userInfo?.userId || '') == vars.data?.userId && (
        <Button
          variant='contained'
          href={`/atc/atc01001s02/${vars.data?.id}`}
          >
          글수정
        </Button>
      ) }
    </section>
    <hr/>
    <section>
      <article>
        <Block> 
          <p> 작성자 : { vars.data.userNm } </p>
          <p> 작성일시 : { print.cdate(vars.data.ctime) } </p>
        </Block>
        <hr/>
        <Block className='w-full overflow-x-auto'>
          <Content html={ vars.data?.contents || '' } />
        </Block>
      </article>
    </section>
  </Container>
  )
})
